/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database_Connection.DB;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dilanka
 */
public class Credit_settle extends javax.swing.JFrame {

    /**
     * Creates new form Credit_settle
     */
    public Credit_settle() {
        initComponents();
        DateandTime();
        Shop_Credit_Table_Loader_Data();
        Customer_Credit_Table_Loader_Data();
        setIcon();
        Jtbl_Credit_Settle_Shop.getTableHeader().setFont(new Font("Helvetica", Font.PLAIN, 15));
        Jtbl_Credit_Settle_Customer.getTableHeader().setFont(new Font("Helvetica", Font.PLAIN, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_Time = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time1 = new javax.swing.JLabel();
        lbl_Date1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        Jtbl_Credit_Settle_Shop = new javax.swing.JTable();
        Jbtn_Credit_Settle_Shop_Pay = new javax.swing.JButton();
        jtxt_Credit_Settle_Shop_Ballence_Credit = new javax.swing.JLabel();
        jtxt_Credit_Settle_Shop_Pay_Price = new javax.swing.JTextField();
        jtxt_Credit_Settle_Shop_Credit_Price = new javax.swing.JLabel();
        jtxt_Credit_Settle_Shop_Supplier_Name = new javax.swing.JLabel();
        jtxt_Credit_Settle_Shop_Supplier_ID = new javax.swing.JLabel();
        jtxt_Credit_Settle_Shop_GRN_Date = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jtxt_Credit_Settle_Shop_GRN_ID = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jtxt_Customer_Search = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        Jtbl_Credit_Settle_Customer = new javax.swing.JTable();
        jtxt_Credit_Settle_Customer_Invoice_ID = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jtxt_Credit_Settle_Customer_Date = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jtxt_Credit_Settle_Customer_Customer_Name = new javax.swing.JLabel();
        jtxt_Credit_Settle_Customer_ID = new javax.swing.JLabel();
        jtxt_Credit_Settle_Customer_Credit_Price = new javax.swing.JLabel();
        jtxt_Credit_Settle_Customer_Pay_Price = new javax.swing.JTextField();
        jtxt_Credit_Settle_Customer_Ballence_Credit = new javax.swing.JLabel();
        Jbtn_Credit_Settle_Customer_Pay = new javax.swing.JButton();
        jtxt_Credit_Settle_Customer_Contact_Number = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jtxt_Customer_Search1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MINO TOP LOGO.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize-38_1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-38_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Lock-38_1.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cancel-38.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_Time.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Time.setText("Time");

        lbl_Date.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date.setText("Date");

        lbl_Time1.setFont(new java.awt.Font("Euphemia", 0, 30)); // NOI18N
        lbl_Time1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Time1.setText("Credit Settle");

        lbl_Date1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbl_Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Date)
                            .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        Jtbl_Credit_Settle_Shop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jtbl_Credit_Settle_Shop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "GRN Date", "Supplier ID", "Supplier Name", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Jtbl_Credit_Settle_Shop.setRowHeight(20);
        Jtbl_Credit_Settle_Shop.getTableHeader().setReorderingAllowed(false);
        Jtbl_Credit_Settle_Shop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtbl_Credit_Settle_ShopMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(Jtbl_Credit_Settle_Shop);
        if (Jtbl_Credit_Settle_Shop.getColumnModel().getColumnCount() > 0) {
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(0).setMinWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(0).setPreferredWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(0).setMaxWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(1).setMinWidth(120);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(1).setPreferredWidth(120);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(1).setMaxWidth(120);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(2).setMinWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(2).setPreferredWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(2).setMaxWidth(100);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(4).setMinWidth(150);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(4).setPreferredWidth(150);
            Jtbl_Credit_Settle_Shop.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        Jbtn_Credit_Settle_Shop_Pay.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        Jbtn_Credit_Settle_Shop_Pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pay-30.png"))); // NOI18N
        Jbtn_Credit_Settle_Shop_Pay.setText("Pay");
        Jbtn_Credit_Settle_Shop_Pay.setFocusable(false);
        Jbtn_Credit_Settle_Shop_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Credit_Settle_Shop_PayActionPerformed(evt);
            }
        });

        jtxt_Credit_Settle_Shop_Ballence_Credit.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_Ballence_Credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Shop_Pay_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_Pay_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Credit_Settle_Shop_Pay_PriceActionPerformed(evt);
            }
        });
        jtxt_Credit_Settle_Shop_Pay_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Shop_Pay_PriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Shop_Pay_PriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Shop_Pay_PriceKeyTyped(evt);
            }
        });

        jtxt_Credit_Settle_Shop_Credit_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_Credit_Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Shop_Supplier_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_Supplier_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Shop_Supplier_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_Supplier_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Shop_GRN_Date.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_GRN_Date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel73.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel73.setText("GRN Date");

        jtxt_Credit_Settle_Shop_GRN_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Shop_GRN_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel72.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel72.setText("GRN ID");

        jLabel74.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel74.setText("Supplier Name");

        jLabel75.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel75.setText("Credit Price");

        jLabel76.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel76.setText("Pay Price");

        jLabel77.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel77.setText("Ballence Credit");

        jtxt_Customer_Search.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel61.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel77)
                        .addContainerGap(722, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel76)
                                            .addGap(53, 53, 53)
                                            .addComponent(jtxt_Credit_Settle_Shop_Pay_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel75)
                                            .addGap(36, 36, 36)
                                            .addComponent(jtxt_Credit_Settle_Shop_Credit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxt_Credit_Settle_Shop_Ballence_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Jbtn_Credit_Settle_Shop_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel74)
                                        .addGap(12, 12, 12)
                                        .addComponent(jtxt_Credit_Settle_Shop_Supplier_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_Credit_Settle_Shop_Supplier_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Customer_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane12)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Credit_Settle_Shop_GRN_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel73)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Credit_Settle_Shop_GRN_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Credit_Settle_Shop_GRN_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxt_Credit_Settle_Shop_GRN_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_Credit_Settle_Shop_Supplier_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxt_Credit_Settle_Shop_Supplier_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Credit_Settle_Shop_Credit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_Credit_Settle_Shop_Pay_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxt_Credit_Settle_Shop_Ballence_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jbtn_Credit_Settle_Shop_Pay)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_Customer_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Icon/shop credit.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Jtbl_Credit_Settle_Customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jtbl_Credit_Settle_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv. No", "Inv. Date", "Customer ID", "Customer Name", "Contact Number", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Jtbl_Credit_Settle_Customer.setRowHeight(20);
        Jtbl_Credit_Settle_Customer.getTableHeader().setReorderingAllowed(false);
        Jtbl_Credit_Settle_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtbl_Credit_Settle_CustomerMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(Jtbl_Credit_Settle_Customer);
        if (Jtbl_Credit_Settle_Customer.getColumnModel().getColumnCount() > 0) {
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(0).setMinWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(0).setPreferredWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(0).setMaxWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(1).setMinWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(1).setPreferredWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(1).setMaxWidth(120);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(2).setMinWidth(100);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(2).setPreferredWidth(100);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(2).setMaxWidth(100);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(4).setMinWidth(150);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(4).setPreferredWidth(150);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(4).setMaxWidth(150);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(5).setMinWidth(150);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(5).setPreferredWidth(150);
            Jtbl_Credit_Settle_Customer.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        jtxt_Credit_Settle_Customer_Invoice_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Invoice_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel79.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel79.setText("Inv. No");

        jLabel80.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel80.setText("Inv. Date");

        jtxt_Credit_Settle_Customer_Date.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel86.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel86.setText("Credit Price");

        jLabel87.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel87.setText("Customer Name");

        jLabel85.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel85.setText("Pay Price");

        jLabel84.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel84.setText("Ballence Credit");

        jtxt_Credit_Settle_Customer_Customer_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Customer_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Customer_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Customer_Credit_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Credit_Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Credit_Settle_Customer_Pay_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Pay_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Credit_Settle_Customer_Pay_PriceActionPerformed(evt);
            }
        });
        jtxt_Credit_Settle_Customer_Pay_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Customer_Pay_PriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Customer_Pay_PriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_Credit_Settle_Customer_Pay_PriceKeyTyped(evt);
            }
        });

        jtxt_Credit_Settle_Customer_Ballence_Credit.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Ballence_Credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Jbtn_Credit_Settle_Customer_Pay.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        Jbtn_Credit_Settle_Customer_Pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/get-cash-30.png"))); // NOI18N
        Jbtn_Credit_Settle_Customer_Pay.setText("Pay");
        Jbtn_Credit_Settle_Customer_Pay.setFocusable(false);
        Jbtn_Credit_Settle_Customer_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_Credit_Settle_Customer_PayActionPerformed(evt);
            }
        });

        jtxt_Credit_Settle_Customer_Contact_Number.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Credit_Settle_Customer_Contact_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel88.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel88.setText("Contact Number");

        jLabel62.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel62.setText("Search");

        jtxt_Customer_Search1.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Customer_Search1jtxt_ADD_Customer_SearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel79)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Credit_Settle_Customer_Invoice_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel80)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Credit_Settle_Customer_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel85)
                            .addComponent(jLabel86)
                            .addComponent(jLabel87, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel84))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jtxt_Credit_Settle_Customer_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_Credit_Settle_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel88)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_Credit_Settle_Customer_Contact_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxt_Credit_Settle_Customer_Pay_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_Credit_Settle_Customer_Credit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_Credit_Settle_Customer_Ballence_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jbtn_Credit_Settle_Customer_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxt_Customer_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(54, Short.MAX_VALUE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Credit_Settle_Customer_Invoice_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxt_Credit_Settle_Customer_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_Credit_Settle_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Credit_Settle_Customer_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Credit_Settle_Customer_Contact_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Credit_Settle_Customer_Credit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))
                        .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel85)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtxt_Credit_Settle_Customer_Pay_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_Credit_Settle_Customer_Ballence_Credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jbtn_Credit_Settle_Customer_Pay))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_Customer_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(338, 338, 338))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Icon/customer credit.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            setExtendedState(Customer.ICONIFIED);
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','System Minimized')");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" +  Login.User_Name  + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Admin Menu')");
        new Admin_Menu().setVisible(true);
        this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Login')");
            new Login().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" +  Login.User_Name  + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Has been Exit from the System')");
            System.exit(0);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
    }//GEN-LAST:event_jPanel2MouseClicked

    private void Jtbl_Credit_Settle_ShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtbl_Credit_Settle_ShopMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Shop.getModel();
        int Selected_Row = Jtbl_Credit_Settle_Shop.getSelectedRow();
        jtxt_Credit_Settle_Shop_GRN_ID.setText(dtm.getValueAt(Selected_Row, 0).toString());
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT * FROM grn G INNER JOIN supplier S ON G.supplier_id = S.supplier_id WHERE G.grn_id = '" + jtxt_Credit_Settle_Shop_GRN_ID.getText() + "'");
            while (rs.next()) {
                jtxt_Credit_Settle_Shop_GRN_Date.setText(rs.getString("G.date"));
                jtxt_Credit_Settle_Shop_Supplier_ID.setText(rs.getString("G.supplier_id"));
                jtxt_Credit_Settle_Shop_Supplier_Name.setText(rs.getString("S.name"));
                jtxt_Credit_Settle_Shop_Credit_Price.setText(rs.getString("G.update_credit_price"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Jtbl_Credit_Settle_ShopMouseClicked

    private void Jbtn_Credit_Settle_Shop_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Credit_Settle_Shop_PayActionPerformed
        if (!jtxt_Credit_Settle_Shop_Pay_Price.getText().isEmpty()) {
            try {
                new DB().putData("UPDATE grn SET update_credit_price='" + jtxt_Credit_Settle_Shop_Ballence_Credit.getText() + "' WHERE grn_id = '" + jtxt_Credit_Settle_Shop_GRN_ID.getText() + "'");
                new DB().putData("INSERT INTO grn_payment (grn_id, payment_price) VALUES('" + jtxt_Credit_Settle_Shop_GRN_ID.getText() + "','" + jtxt_Credit_Settle_Shop_Pay_Price.getText() + "')");
                JOptionPane.showMessageDialog(this, "Payment Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                jtxt_Credit_Settle_Shop_GRN_ID.setText(null);
                jtxt_Credit_Settle_Shop_GRN_Date.setText(null);
                jtxt_Credit_Settle_Shop_Supplier_Name.setText(null);
                jtxt_Credit_Settle_Shop_Supplier_ID.setText(null);
                jtxt_Credit_Settle_Shop_Credit_Price.setText(null);
                jtxt_Credit_Settle_Shop_Pay_Price.setText(null);
                jtxt_Credit_Settle_Shop_Ballence_Credit.setText(null);
                Shop_Credit_Table_Loader_Data();
                //                GRN_Payment_Table_Loader();
                //                Invoice_Payment_Table_Total();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_Jbtn_Credit_Settle_Shop_PayActionPerformed

    private void jtxt_Credit_Settle_Shop_Pay_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Shop_Pay_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Credit_Settle_Shop_Pay_PriceActionPerformed

    private void jtxt_Credit_Settle_Shop_Pay_PriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyPressed

    }//GEN-LAST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyPressed

    private void jtxt_Credit_Settle_Shop_Pay_PriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyReleased
        if (!jtxt_Credit_Settle_Shop_Pay_Price.getText().isEmpty()) {

            double QTY = Double.parseDouble(jtxt_Credit_Settle_Shop_Credit_Price.getText().toString());
            double UP = Double.parseDouble(jtxt_Credit_Settle_Shop_Pay_Price.getText().toString());
            double tot = QTY - UP;
            jtxt_Credit_Settle_Shop_Ballence_Credit.setText(new DecimalFormat("0.00").format(tot));
        } else {
            jtxt_Credit_Settle_Shop_Ballence_Credit.setText("0.00");
        }
    }//GEN-LAST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyReleased

    private void jtxt_Credit_Settle_Shop_Pay_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyTyped

    }//GEN-LAST:event_jtxt_Credit_Settle_Shop_Pay_PriceKeyTyped

    private void jtxt_Credit_Settle_Customer_Pay_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyTyped

    private void jtxt_Credit_Settle_Customer_Pay_PriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyReleased
        double QTY = Double.parseDouble(jtxt_Credit_Settle_Customer_Credit_Price.getText().toString());
        double UP = Double.parseDouble(jtxt_Credit_Settle_Customer_Pay_Price.getText().toString());
        double tot = QTY - UP;
        jtxt_Credit_Settle_Customer_Ballence_Credit.setText(new DecimalFormat("0.00").format(tot));
    }//GEN-LAST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyReleased

    private void jtxt_Credit_Settle_Customer_Pay_PriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Credit_Settle_Customer_Pay_PriceKeyPressed

    private void jtxt_Credit_Settle_Customer_Pay_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Credit_Settle_Customer_Pay_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Credit_Settle_Customer_Pay_PriceActionPerformed

    private void Jbtn_Credit_Settle_Customer_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_Credit_Settle_Customer_PayActionPerformed
        if (!jtxt_Credit_Settle_Customer_Pay_Price.getText().isEmpty()) {
            try {
                new DB().putData("UPDATE invoice SET customer_credit='" + jtxt_Credit_Settle_Customer_Ballence_Credit.getText() + "' WHERE invoice_id = '" + jtxt_Credit_Settle_Customer_Invoice_ID.getText() + "'");
                new DB().putData("INSERT INTO invoice_payment (invoice_invoice_id,date,time,cash,balance) VALUES('" + jtxt_Credit_Settle_Customer_Invoice_ID.getText() + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','" + jtxt_Credit_Settle_Customer_Pay_Price.getText() + "','0')");
                JOptionPane.showMessageDialog(this, "Payment Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                jtxt_Credit_Settle_Customer_Date.setText(null);
                jtxt_Credit_Settle_Customer_Customer_Name.setText(null);
                jtxt_Credit_Settle_Customer_ID.setText(null);
                jtxt_Credit_Settle_Customer_Credit_Price.setText(null);
                jtxt_Credit_Settle_Customer_Pay_Price.setText(null);
                jtxt_Credit_Settle_Customer_Ballence_Credit.setText(null);
                jtxt_Credit_Settle_Customer_Contact_Number.setText(null);
                Report_Customer_Credit();
                jtxt_Credit_Settle_Customer_Invoice_ID.setText(null);
                Customer_Credit_Table_Loader_Data();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_Jbtn_Credit_Settle_Customer_PayActionPerformed

    private void Jtbl_Credit_Settle_CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtbl_Credit_Settle_CustomerMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Customer.getModel();
        int Selected_Row = Jtbl_Credit_Settle_Customer.getSelectedRow();
        jtxt_Credit_Settle_Customer_Invoice_ID.setText(dtm.getValueAt(Selected_Row, 0).toString());
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT * FROM invoice I INNER JOIN customer C ON I.customer_id = C.customer_id WHERE I.invoice_id = '" + jtxt_Credit_Settle_Customer_Invoice_ID.getText() + "'");
            while (rs.next()) {
                jtxt_Credit_Settle_Customer_Date.setText(rs.getString("I.date"));
                jtxt_Credit_Settle_Customer_ID.setText(rs.getString("I.customer_id"));
                jtxt_Credit_Settle_Customer_Customer_Name.setText(rs.getString("C.name"));
                jtxt_Credit_Settle_Customer_Credit_Price.setText(rs.getString("I.customer_credit"));
                jtxt_Credit_Settle_Customer_Contact_Number.setText(rs.getString("C.contact_no"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Jtbl_Credit_Settle_CustomerMouseClicked

    private void jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Shop.getModel();
        try {
            ResultSet rs = new DB().getData("select * from grn INNER JOIN supplier ON grn.supplier_id=supplier.supplier_id where supplier.name like '%" + jtxt_Customer_Search.getText() + "%' && grn.update_credit_price !='0' ");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("grn.grn_id"));
                v.add(rs.getString("grn.date"));
                v.add(rs.getString("grn.supplier_id"));
                v.add(rs.getString("supplier.name"));
                v.add(rs.getString("grn.update_credit_price"));
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased

    private void jtxt_Customer_Search1jtxt_ADD_Customer_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Customer_Search1jtxt_ADD_Customer_SearchKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Customer.getModel();
        try {
            ResultSet rs = new DB().getData("select * from invoice INNER JOIN customer ON invoice.customer_id = customer.customer_id where customer.name like '%" + jtxt_Customer_Search1.getText() + "%' && invoice.customer_credit !='0'");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("invoice.invoice_id"));
                v.add(rs.getString("invoice.date"));
                v.add(rs.getString("invoice.customer_id"));
                v.add(rs.getString("customer.name"));
                v.add(rs.getString("customer.contact_no"));
                v.add(rs.getString("invoice.customer_credit"));
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxt_Customer_Search1jtxt_ADD_Customer_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credit_settle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credit_settle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credit_settle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credit_settle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credit_settle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_Credit_Settle_Customer_Pay;
    private javax.swing.JButton Jbtn_Credit_Settle_Shop_Pay;
    private javax.swing.JTable Jtbl_Credit_Settle_Customer;
    private javax.swing.JTable Jtbl_Credit_Settle_Shop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Ballence_Credit;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Contact_Number;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Credit_Price;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Customer_Name;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Date;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_ID;
    private javax.swing.JLabel jtxt_Credit_Settle_Customer_Invoice_ID;
    private javax.swing.JTextField jtxt_Credit_Settle_Customer_Pay_Price;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_Ballence_Credit;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_Credit_Price;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_GRN_Date;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_GRN_ID;
    private javax.swing.JTextField jtxt_Credit_Settle_Shop_Pay_Price;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_Supplier_ID;
    private javax.swing.JLabel jtxt_Credit_Settle_Shop_Supplier_Name;
    private javax.swing.JTextField jtxt_Customer_Search;
    private javax.swing.JTextField jtxt_Customer_Search1;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Date1;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Time1;
    // End of variables declaration//GEN-END:variables

private void DateandTime() {
        Timer t = new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf_Time = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat sdf_Date = new SimpleDateFormat("YYYY  MMMM  dd EEEE");
                SimpleDateFormat sdf_Date2 = new SimpleDateFormat("YYYY-MM-dd");
                String time = sdf_Time.format(d);
                String Date = sdf_Date.format(d);
                String Date2 = sdf_Date2.format(d);
                lbl_Time.setText(time);
                lbl_Date.setText(Date);
                lbl_Date1.setText(Date2);
            }
        });
        t.start();
    }

private void Shop_Credit_Table_Loader_Data() {
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Shop.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet set = new DB().getData("SELECT * FROM grn G INNER JOIN supplier S ON G.supplier_id = S.supplier_id WHERE G.update_credit_price !='0' ");

            while (set.next()) {
                Vector v = new Vector();
                v.add(set.getString("G.grn_id"));
                v.add(set.getString("G.date"));
                v.add(set.getString("G.supplier_id"));
                v.add(set.getString("S.name"));
                v.add(set.getString("G.update_credit_price"));

                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }


private void Customer_Credit_Table_Loader_Data() {
        DefaultTableModel dtm = (DefaultTableModel) Jtbl_Credit_Settle_Customer.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet set = new DB().getData("SELECT * FROM invoice I INNER JOIN customer C ON I.customer_id = C.customer_id WHERE I.customer_credit !='0' ");

            while (set.next()) {
                Vector v = new Vector();
                v.add(set.getString("I.invoice_id"));
                v.add(set.getString("I.date"));
                v.add(set.getString("I.customer_id"));
                v.add(set.getString("C.name"));
                v.add(set.getString("C.contact_no"));
                v.add(set.getString("I.customer_credit"));

                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }

private void Report_Customer_Credit() {
        try {
            String reportSourse = "src\\report\\VIRUVO_Customer_Credit_Payment.jrxml";
            HashMap<String, Object> params = new HashMap<String, Object>();
            params.put("InvoiceID", Integer.parseInt(jtxt_Credit_Settle_Customer_Invoice_ID.getText()));
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSourse);
            Connection connseacrch = new Database_Connection.DB().myCon();
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, connseacrch);
            JasperPrintManager.printReport(jasperPrint, false);
            connseacrch.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
    }

}
