/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database_Connection.DB;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilanka
 */
public class Customer extends javax.swing.JFrame {
    
    private String gen;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        DateandTime();
        setIcon();
        Customer_ID_Auto_Loader();
        Customer_Table_Loader_Data();
        jtbl_Customer.getTableHeader().setFont(new Font("Helvetica", Font.PLAIN, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_Time = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time1 = new javax.swing.JLabel();
        lbl_Date1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jtbl_Customer = new javax.swing.JTable();
        jtxt_Customer_Search = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jCmb_Customer_Status = new javax.swing.JComboBox();
        jtxt_Customer_Address = new javax.swing.JTextField();
        jtxt_Customer__Email = new javax.swing.JTextField();
        jtxt_Customer_Phone_number = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jlbl_Customer_ID = new javax.swing.JLabel();
        jtxt_Customer_Name = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jbtn_ADD_Customer_update = new javax.swing.JButton();
        jbtn_ADD_Customer_Save = new javax.swing.JButton();
        jbtn_ADD_Customer_Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MINO TOP LOGO.png"))); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize-38_1.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-38_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Lock-38_1.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cancel-38.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_Time.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Time.setText("Time");

        lbl_Date.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date.setText("Date");

        lbl_Time1.setFont(new java.awt.Font("Euphemia", 0, 30)); // NOI18N
        lbl_Time1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Time1.setText("Customers");

        lbl_Date1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbl_Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_Time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Date)
                            .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jtbl_Customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbl_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Phone Number", "Email", "Address", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_Customer.setRowHeight(20);
        jtbl_Customer.getTableHeader().setReorderingAllowed(false);
        jtbl_Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_Customerjtbl_ADD_CustomerMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(jtbl_Customer);
        if (jtbl_Customer.getColumnModel().getColumnCount() > 0) {
            jtbl_Customer.getColumnModel().getColumn(0).setMinWidth(100);
            jtbl_Customer.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtbl_Customer.getColumnModel().getColumn(0).setMaxWidth(100);
            jtbl_Customer.getColumnModel().getColumn(2).setMinWidth(80);
            jtbl_Customer.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtbl_Customer.getColumnModel().getColumn(2).setMaxWidth(80);
            jtbl_Customer.getColumnModel().getColumn(3).setMinWidth(130);
            jtbl_Customer.getColumnModel().getColumn(3).setPreferredWidth(130);
            jtbl_Customer.getColumnModel().getColumn(3).setMaxWidth(130);
            jtbl_Customer.getColumnModel().getColumn(6).setMinWidth(100);
            jtbl_Customer.getColumnModel().getColumn(6).setPreferredWidth(100);
            jtbl_Customer.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        jtxt_Customer_Search.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel61.setText("Search");

        jCmb_Customer_Status.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jCmb_Customer_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Deactive" }));
        jCmb_Customer_Status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmb_Customer_StatusKeyPressed(evt);
            }
        });

        jtxt_Customer_Address.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Customer_Addressjtxt_ADD_Customer_AddressActionPerformed(evt);
            }
        });

        jtxt_Customer__Email.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer__Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Customer__Emailjtxt_ADD_Customer_EmailActionPerformed(evt);
            }
        });

        jtxt_Customer_Phone_number.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Customer_Phone_numberjtxt_ADD_Customer_Phone_numberActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel62.setText("Phone Number");

        jLabel90.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel90.setText("Email");

        jLabel91.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel91.setText("Address");

        jLabel92.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel92.setText("Customer ID");

        jlbl_Customer_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Customer_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Customer_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Customer_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Customer_Namejtxt_ADD_Customer_NameActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        female.setText("Female");
        female.setContentAreaFilled(false);
        female.setFocusable(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalefemaleActionPerformed(evt);
            }
        });

        male.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        male.setSelected(true);
        male.setText("Male");
        male.setContentAreaFilled(false);
        male.setFocusable(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malemaleActionPerformed(evt);
            }
        });

        jLabel93.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel93.setText("Gender");

        jLabel94.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel94.setText("Name");

        jbtn_ADD_Customer_update.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_ADD_Customer_update.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_ADD_Customer_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update-color-24.png"))); // NOI18N
        jbtn_ADD_Customer_update.setText("Update");
        jbtn_ADD_Customer_update.setFocusable(false);
        jbtn_ADD_Customer_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ADD_Customer_updatejbtn_ADD_Customer_updateActionPerformed(evt);
            }
        });

        jbtn_ADD_Customer_Save.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_ADD_Customer_Save.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_ADD_Customer_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save-color-24.png"))); // NOI18N
        jbtn_ADD_Customer_Save.setText("Save");
        jbtn_ADD_Customer_Save.setFocusable(false);
        jbtn_ADD_Customer_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ADD_Customer_Savejbtn_ADD_Customer_SaveActionPerformed(evt);
            }
        });

        jbtn_ADD_Customer_Clear.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_ADD_Customer_Clear.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_ADD_Customer_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/clear-color-24.png"))); // NOI18N
        jbtn_ADD_Customer_Clear.setText("Clear");
        jbtn_ADD_Customer_Clear.setFocusable(false);
        jbtn_ADD_Customer_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ADD_Customer_Clearjbtn_ADD_Customer_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jtxt_Customer_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel93)
                                        .addComponent(jLabel90)
                                        .addComponent(jLabel92)
                                        .addComponent(jLabel94)
                                        .addComponent(jLabel62))
                                    .addGap(7, 7, 7)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlbl_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addComponent(male)
                                            .addGap(18, 18, 18)
                                            .addComponent(female))
                                        .addComponent(jtxt_Customer_Phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxt_Customer__Email, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxt_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jCmb_Customer_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jbtn_ADD_Customer_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_ADD_Customer_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_ADD_Customer_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Customer_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl_Customer_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(male, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(female, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Customer_Phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_Customer__Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_Customer_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_ADD_Customer_Clear)
                        .addComponent(jbtn_ADD_Customer_update)
                        .addComponent(jbtn_ADD_Customer_Save))
                    .addComponent(jCmb_Customer_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_Customer_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            setExtendedState(Customer.ICONIFIED);
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','System Minimized')");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Admin Menu')");
        new Admin_Menu().setVisible(true);
        this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Login')");
            new Login().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" +  Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Has been Exit from the System')");
            System.exit(0);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtbl_Customerjtbl_ADD_CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_Customerjtbl_ADD_CustomerMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Customer.getModel();
        int Selected_Row = jtbl_Customer.getSelectedRow();
        jlbl_Customer_ID.setText(dtm.getValueAt(Selected_Row, 0).toString());
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT * FROM customer WHERE customer_id = '" + jlbl_Customer_ID.getText() + "'");
            while (rs.next()) {
                jtxt_Customer_Name.setText(rs.getString("name"));
                if (rs.getString("gender").equals("Male")) {
                    male.setSelected(true);
                } else {
                    female.setSelected(true);
                }
                jtxt_Customer_Phone_number.setText(rs.getString("contact_no"));
                jtxt_Customer__Email.setText(rs.getString("email"));
                jtxt_Customer_Address.setText(rs.getString("address"));
                if (rs.getString("status").equals("1")) {
                    jCmb_Customer_Status.setSelectedItem("Active");
                } else {
                    jCmb_Customer_Status.setSelectedItem("Deactive");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jtbl_Customerjtbl_ADD_CustomerMouseClicked

    private void jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Customer.getModel();
        try {
            ResultSet rs = new DB().getData("select * from customer where name like '%" + jtxt_Customer_Search.getText() + "%'");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("customer_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("contact_no"));
                v.add(rs.getString("email"));
                v.add(rs.getString("address"));
                if (rs.getString("status").equals("1")) {
                    v.add("Active");
                }
                if (rs.getString("status").equals("0")) {
                    v.add("Deactive");
                }
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxt_Customer_Searchjtxt_ADD_Customer_SearchKeyReleased

    private void jtxt_Customer_Addressjtxt_ADD_Customer_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Customer_Addressjtxt_ADD_Customer_AddressActionPerformed
        jCmb_Customer_Status.grabFocus();
    }//GEN-LAST:event_jtxt_Customer_Addressjtxt_ADD_Customer_AddressActionPerformed

    private void jtxt_Customer__Emailjtxt_ADD_Customer_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Customer__Emailjtxt_ADD_Customer_EmailActionPerformed
        jtxt_Customer_Address.grabFocus();
    }//GEN-LAST:event_jtxt_Customer__Emailjtxt_ADD_Customer_EmailActionPerformed

    private void jtxt_Customer_Phone_numberjtxt_ADD_Customer_Phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Customer_Phone_numberjtxt_ADD_Customer_Phone_numberActionPerformed
        jtxt_Customer__Email.grabFocus();
    }//GEN-LAST:event_jtxt_Customer_Phone_numberjtxt_ADD_Customer_Phone_numberActionPerformed

    private void jtxt_Customer_Namejtxt_ADD_Customer_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Customer_Namejtxt_ADD_Customer_NameActionPerformed
        jtxt_Customer_Phone_number.grabFocus();
    }//GEN-LAST:event_jtxt_Customer_Namejtxt_ADD_Customer_NameActionPerformed

    private void femalefemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalefemaleActionPerformed
        jtxt_Customer_Phone_number.grabFocus();
    }//GEN-LAST:event_femalefemaleActionPerformed

    private void malemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malemaleActionPerformed
        jtxt_Customer_Phone_number.grabFocus();
    }//GEN-LAST:event_malemaleActionPerformed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked

    }//GEN-LAST:event_jPanel9MouseClicked

    private void jbtn_ADD_Customer_updatejbtn_ADD_Customer_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ADD_Customer_updatejbtn_ADD_Customer_updateActionPerformed
        if (!jlbl_Customer_ID.getText().isEmpty() && !jtxt_Customer_Name.getText().isEmpty()) {
            try {
                if (male.isSelected()) {
                    gen = "Male";
                } else {
                    gen = "Female";
                }

                int Status = 0;

                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Active")) {
                    Status += 1;
                }
                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Deactive")) {
                    Status += 0;
                }
                new DB().putData("UPDATE customer SET name='" + jtxt_Customer_Name.getText() + "',gender='" + gen + "',contact_no='" + jtxt_Customer_Phone_number.getText() + "',email='" + jtxt_Customer__Email.getText() + "',address='" + jtxt_Customer_Address.getText() + "',status='" + Status + "' WHERE customer_id = '" + jlbl_Customer_ID.getText() + "'");
                JOptionPane.showMessageDialog(this, "Customer Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                jtxt_Customer_Name.setText(null);
                male.setSelected(true);
                jtxt_Customer_Phone_number.setText(null);
                jtxt_Customer__Email.setText(null);
                jtxt_Customer_Address.setText(null);
                jCmb_Customer_Status.setSelectedIndex(0);
                jtxt_Customer_Name.grabFocus();
                Customer_ID_Auto_Loader();
                Customer_Table_Loader_Data();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jbtn_ADD_Customer_updatejbtn_ADD_Customer_updateActionPerformed

    private void jbtn_ADD_Customer_Savejbtn_ADD_Customer_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ADD_Customer_Savejbtn_ADD_Customer_SaveActionPerformed
        if (!jlbl_Customer_ID.getText().isEmpty() && !jtxt_Customer_Name.getText().isEmpty()) {
            try {

                int Status = 0;

                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Active")) {
                    Status += 1;
                }
                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Deactive")) {
                    Status += 0;
                }

                if (male.isSelected()) {
                    gen = "Male";
                } else {
                    gen = "Female";
                }

                new Database_Connection.DB().putData("insert into customer (customer_id,name,gender,contact_no,email,address,status) values('" + jlbl_Customer_ID.getText() + "','" + jtxt_Customer_Name.getText() + "','" + gen + "','" + jtxt_Customer_Phone_number.getText() + "','" + jtxt_Customer__Email.getText() + "','" + jtxt_Customer_Address.getText() + "','" + Status + "')");
                JOptionPane.showMessageDialog(this, "Customer Registered Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                jtxt_Customer_Name.setText(null);
                male.setSelected(true);
                jtxt_Customer_Phone_number.setText(null);
                jtxt_Customer__Email.setText(null);
                jtxt_Customer_Address.setText(null);
                jCmb_Customer_Status.setSelectedIndex(0);
                Customer_ID_Auto_Loader();
                Customer_Table_Loader_Data();

            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Check All Input Field", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_ADD_Customer_Savejbtn_ADD_Customer_SaveActionPerformed

    private void jbtn_ADD_Customer_Clearjbtn_ADD_Customer_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ADD_Customer_Clearjbtn_ADD_Customer_ClearActionPerformed
        jtxt_Customer_Name.setText(null);
        male.setSelected(true);
        jtxt_Customer_Phone_number.setText(null);
        jtxt_Customer__Email.setText(null);
        jtxt_Customer_Address.setText(null);
        jCmb_Customer_Status.setSelectedIndex(0);
        jtxt_Customer_Search.setText(null);
        jtxt_Customer_Name.grabFocus();
        Customer_ID_Auto_Loader();
        Customer_Table_Loader_Data();
    }//GEN-LAST:event_jbtn_ADD_Customer_Clearjbtn_ADD_Customer_ClearActionPerformed

    private void jCmb_Customer_StatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmb_Customer_StatusKeyPressed
        char c = evt.getKeyChar();
        if (c == evt.VK_ENTER) {
            if (!jlbl_Customer_ID.getText().isEmpty() && !jtxt_Customer_Name.getText().isEmpty()) {
            try {

                int Status = 0;

                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Active")) {
                    Status += 1;
                }
                if (jCmb_Customer_Status.getSelectedItem().toString().equals("Deactive")) {
                    Status += 0;
                }

                if (male.isSelected()) {
                    gen = "Male";
                } else {
                    gen = "Female";
                }

                new Database_Connection.DB().putData("insert into customer (customer_id,name,gender,contact_no,email,address,status) values('" + jlbl_Customer_ID.getText() + "','" + jtxt_Customer_Name.getText() + "','" + gen + "','" + jtxt_Customer_Phone_number.getText() + "','" + jtxt_Customer__Email.getText() + "','" + jtxt_Customer_Address.getText() + "','" + Status + "')");
                JOptionPane.showMessageDialog(this, "Customer Registered Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                jtxt_Customer_Name.setText(null);
                male.setSelected(true);
                jtxt_Customer_Phone_number.setText(null);
                jtxt_Customer__Email.setText(null);
                jtxt_Customer_Address.setText(null);
                jCmb_Customer_Status.setSelectedIndex(0);
                jtxt_Customer_Name.grabFocus();
                Customer_ID_Auto_Loader();
                Customer_Table_Loader_Data();

            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Check All Input Field", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_jCmb_Customer_StatusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCmb_Customer_Status;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JButton jbtn_ADD_Customer_Clear;
    private javax.swing.JButton jbtn_ADD_Customer_Save;
    private javax.swing.JButton jbtn_ADD_Customer_update;
    private javax.swing.JLabel jlbl_Customer_ID;
    private javax.swing.JTable jtbl_Customer;
    private javax.swing.JTextField jtxt_Customer_Address;
    private javax.swing.JTextField jtxt_Customer_Name;
    private javax.swing.JTextField jtxt_Customer_Phone_number;
    private javax.swing.JTextField jtxt_Customer_Search;
    private javax.swing.JTextField jtxt_Customer__Email;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Date1;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Time1;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables

    private void DateandTime() {
        Timer t = new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf_Time = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat sdf_Date = new SimpleDateFormat("YYYY  MMMM  dd EEEE");
                SimpleDateFormat sdf_Date1 = new SimpleDateFormat("YYYY-MM-dd");
                String time = sdf_Time.format(d);
                String Date = sdf_Date.format(d);
                String Date1 = sdf_Date1.format(d);
                lbl_Time.setText(time);
                lbl_Date.setText(Date);
                lbl_Date1.setText(Date1);
            }
        });
        t.start();
    }
    
    private void Customer_ID_Auto_Loader() {
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT MAX(customer_id) AS LargestID FROM customer;");
            if (rs.next()) {
                String id = rs.getString("LargestID");
                jlbl_Customer_ID.setText(Integer.parseInt(id) + 1 + "");
            }
        } catch (Exception e) {
            System.out.println(e);
            jlbl_Customer_ID.setText("1000");
        }
    }
    
    private void Customer_Table_Loader_Data() {
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Customer.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet set = new Database_Connection.DB().getData("SELECT * FROM customer where customer_id !='1000'");

            while (set.next()) {
                Vector v = new Vector();
                v.add(set.getString("customer_id"));
                v.add(set.getString("name"));
                v.add(set.getString("gender"));
                v.add(set.getString("contact_no"));
                v.add(set.getString("email"));
                v.add(set.getString("address"));
                if (set.getString("status").equals("1")) {
                    v.add("Active");
                }
                if (set.getString("status").equals("0")) {
                    v.add("Deactive");
                }
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
    }

}
