/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database_Connection.DB;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilanka
 */
public class Price_Update extends javax.swing.JFrame {

    /**
     * Creates new form Price_Update
     */
    public Price_Update() {
        initComponents();
        DateandTime();
        setIcon();
        jtbl_Price_Update.getTableHeader().setFont(new Font("Helvetica", Font.PLAIN, 15));
        Price_Update_Table_Loader_Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_Time = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time1 = new javax.swing.JLabel();
        lbl_Date1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jlbl_Price_Update_GRN_ID = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jlbl_Price_Update_GRN_Date = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jtxtl_Price_Update_Supplier_Name = new javax.swing.JLabel();
        jtxt_Price_Supplier_ID = new javax.swing.JLabel();
        jlbl_Price_Update_Supplier_Price = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jlbl_Price_Update_Item_ID = new javax.swing.JLabel();
        jlbl_Price_Update_Product_Name = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jlbl_Price_Update_Update_Selling_Price = new javax.swing.JTextField();
        jlbl_Price_Update_Stock_Selling_Price = new javax.swing.JLabel();
        jbtn_Price_Update_Price_Update = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtbl_Price_Update = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        jtxt_Price_Update_Search = new javax.swing.JTextField();
        jlbl_Price_Update_Discount = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MINO TOP LOGO.png"))); // NOI18N

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize-38_1.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-38_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Lock-38_1.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cancel-38.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_Time.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Time.setText("Time");

        lbl_Date.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date.setText("Date");

        lbl_Time1.setFont(new java.awt.Font("Euphemia", 0, 30)); // NOI18N
        lbl_Time1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Time1.setText("Price Update");

        lbl_Date1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbl_Time1)
                .addGap(29, 29, 29)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_Time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Date))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel63.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel63.setText("GRN ID");

        jlbl_Price_Update_GRN_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_GRN_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel64.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel64.setText("GRN Date");

        jlbl_Price_Update_GRN_Date.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_GRN_Date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel65.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel65.setText("Supplier Name");

        jtxtl_Price_Update_Supplier_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxtl_Price_Update_Supplier_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jtxt_Price_Supplier_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Price_Supplier_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jlbl_Price_Update_Supplier_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_Supplier_Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel71.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel71.setText("GRN Supplier Price");

        jlbl_Price_Update_Item_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_Item_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jlbl_Price_Update_Product_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_Product_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel69.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel69.setText("Item Name");

        jLabel67.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel67.setText("Stock Selling Price");

        jLabel68.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel68.setText("Update Selling Price");

        jlbl_Price_Update_Update_Selling_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N

        jlbl_Price_Update_Stock_Selling_Price.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_Stock_Selling_Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jbtn_Price_Update_Price_Update.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_Price_Update_Price_Update.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_Price_Update_Price_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        jbtn_Price_Update_Price_Update.setFocusable(false);
        jbtn_Price_Update_Price_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Price_Update_Price_UpdateActionPerformed(evt);
            }
        });

        jtbl_Price_Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbl_Price_Update.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN ID", "GRN Date", "Supplier Name", "Item ID", "Item Name", "Stock Qty", "Supplier Price", "Stock Selling Price", "Now Selling Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_Price_Update.setFocusable(false);
        jtbl_Price_Update.setRowHeight(20);
        jtbl_Price_Update.getTableHeader().setReorderingAllowed(false);
        jtbl_Price_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_Price_UpdateMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jtbl_Price_Update);
        if (jtbl_Price_Update.getColumnModel().getColumnCount() > 0) {
            jtbl_Price_Update.getColumnModel().getColumn(0).setMinWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(0).setMaxWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(1).setMinWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(1).setMaxWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(3).setMinWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(3).setPreferredWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(3).setMaxWidth(70);
            jtbl_Price_Update.getColumnModel().getColumn(5).setMinWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(5).setPreferredWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(5).setMaxWidth(100);
            jtbl_Price_Update.getColumnModel().getColumn(6).setMinWidth(130);
            jtbl_Price_Update.getColumnModel().getColumn(6).setPreferredWidth(130);
            jtbl_Price_Update.getColumnModel().getColumn(6).setMaxWidth(130);
            jtbl_Price_Update.getColumnModel().getColumn(7).setMinWidth(0);
            jtbl_Price_Update.getColumnModel().getColumn(7).setPreferredWidth(0);
            jtbl_Price_Update.getColumnModel().getColumn(7).setMaxWidth(0);
            jtbl_Price_Update.getColumnModel().getColumn(8).setMinWidth(130);
            jtbl_Price_Update.getColumnModel().getColumn(8).setPreferredWidth(130);
            jtbl_Price_Update.getColumnModel().getColumn(8).setMaxWidth(130);
        }

        jLabel57.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel57.setText("Search Item Name");

        jtxt_Price_Update_Search.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Price_Update_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Price_Update_SearchKeyReleased(evt);
            }
        });

        jlbl_Price_Update_Discount.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_Price_Update_Discount.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel70.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel70.setText("Discount (default %)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel63))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jlbl_Price_Update_Product_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbl_Price_Update_Item_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jlbl_Price_Update_GRN_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbl_Price_Update_GRN_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbl_Price_Update_Supplier_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addGap(49, 49, 49)
                                .addComponent(jtxtl_Price_Update_Supplier_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_Price_Supplier_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_Price_Update_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addComponent(jLabel67))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_Price_Update_Stock_Selling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_Price_Update_Price_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_Price_Update_Update_Selling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jlbl_Price_Update_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbl_Price_Update_GRN_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_Price_Update_GRN_Date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_Price_Update_Product_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_Price_Update_Item_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtl_Price_Update_Supplier_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Price_Supplier_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jlbl_Price_Update_Supplier_Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_Price_Update_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_Price_Update_Stock_Selling_Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbl_Price_Update_Update_Selling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbl_Price_Update_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_Price_Update_Price_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            setExtendedState(Customer.ICONIFIED);
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','System Minimized')");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" +  Login.User_Name  + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Admin Menu')");
        new Admin_Menu().setVisible(true);
        this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Login')");
            new Login().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" +  Login.User_Name  + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Has been Exit from the System')");
            System.exit(0);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_Price_Update_Price_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Price_Update_Price_UpdateActionPerformed
        if (!jlbl_Price_Update_Update_Selling_Price.getText().isEmpty() || !jlbl_Price_Update_Discount.getText().isEmpty()) {
            if (!jlbl_Price_Update_Update_Selling_Price.getText().isEmpty()) {

                try {
                    new Database_Connection.DB().putData("UPDATE grn_stock GS INNER JOIN grn_item GI ON GS.grn_id = GI.grn_id SET GS.selling_price='" + jlbl_Price_Update_Update_Selling_Price.getText() + "' WHERE GS.item_id = '" + jlbl_Price_Update_Item_ID.getText() + "' && GS.grn_id = '" + jlbl_Price_Update_GRN_ID.getText() + "' ");
                    new Database_Connection.DB().putData("UPDATE grn_item GI SET GI.discount='" + jlbl_Price_Update_Discount.getText() + "' WHERE GI.item_id = '" + jlbl_Price_Update_Item_ID.getText() + "' && GI.grn_id = '" + jlbl_Price_Update_GRN_ID.getText() + "' ");
                    JOptionPane.showMessageDialog(this, "GRN Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                    jlbl_Price_Update_Item_ID.setText(null);
                    jtxt_Price_Supplier_ID.setText(null);
                    jlbl_Price_Update_GRN_ID.setText(null);
                    jlbl_Price_Update_GRN_Date.setText(null);
                    jlbl_Price_Update_Product_Name.setText(null);
                    jtxtl_Price_Update_Supplier_Name.setText(null);
                    jlbl_Price_Update_Supplier_Price.setText(null);
                    jlbl_Price_Update_Stock_Selling_Price.setText(null);
                    jlbl_Price_Update_Update_Selling_Price.setText(null);
                    jlbl_Price_Update_Discount.setText(null);
                    Price_Update_Table_Loader_Data();

                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                try {
                    new Database_Connection.DB().putData("UPDATE grn_item GI SET GI.discount='" + jlbl_Price_Update_Discount.getText() + "' WHERE GI.item_id = '" + jlbl_Price_Update_Item_ID.getText() + "' && GI.grn_id = '" + jlbl_Price_Update_GRN_ID.getText() + "' ");
                    JOptionPane.showMessageDialog(this, "GRN Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);

                    jlbl_Price_Update_Item_ID.setText(null);
                    jtxt_Price_Supplier_ID.setText(null);
                    jlbl_Price_Update_GRN_ID.setText(null);
                    jlbl_Price_Update_GRN_Date.setText(null);
                    jlbl_Price_Update_Product_Name.setText(null);
                    jtxtl_Price_Update_Supplier_Name.setText(null);
                    jlbl_Price_Update_Supplier_Price.setText(null);
                    jlbl_Price_Update_Stock_Selling_Price.setText(null);
                    jlbl_Price_Update_Update_Selling_Price.setText(null);
                    jlbl_Price_Update_Discount.setText(null);
                    Price_Update_Table_Loader_Data();

                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Check All Input Field", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_Price_Update_Price_UpdateActionPerformed

    private void jtbl_Price_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_Price_UpdateMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Price_Update.getModel();
        int Selected_Row = jtbl_Price_Update.getSelectedRow();
        jlbl_Price_Update_GRN_ID.setText(dtm.getValueAt(Selected_Row, 0).toString());
        jlbl_Price_Update_Item_ID.setText(dtm.getValueAt(Selected_Row, 3).toString());
        jlbl_Price_Update_GRN_Date.setText(dtm.getValueAt(Selected_Row, 1).toString());
        jlbl_Price_Update_Product_Name.setText(dtm.getValueAt(Selected_Row, 4).toString());
        jtxtl_Price_Update_Supplier_Name.setText(dtm.getValueAt(Selected_Row, 2).toString());
        jlbl_Price_Update_Supplier_Price.setText(dtm.getValueAt(Selected_Row, 6).toString());
        jlbl_Price_Update_Stock_Selling_Price.setText(dtm.getValueAt(Selected_Row, 7).toString());

        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT * FROM grn G INNER JOIN grn_item GI ON G.grn_id = GI.grn_id INNER JOIN grn_stock GS ON G.grn_id = GS.grn_id INNER JOIN supplier S ON G.supplier_id = S.supplier_id INNER JOIN item I ON GI.item_id = I.item_id WHERE G.grn_id = '" + jlbl_Price_Update_GRN_ID.getText() + "' and GI.item_id = '" + jlbl_Price_Update_Item_ID.getText() + "'");
            while (rs.next()) {
                jtxt_Price_Supplier_ID.setText(rs.getString("G.supplier_id"));
                jlbl_Price_Update_Discount.setText(rs.getString("GI.discount"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jtbl_Price_UpdateMouseClicked

    private void jtxt_Price_Update_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Price_Update_SearchKeyReleased

        DefaultTableModel dtm = (DefaultTableModel) jtbl_Price_Update.getModel();
        try {
            ResultSet rs = new DB().getData("SELECT * FROM grn G INNER JOIN grn_item GI ON G.grn_id = GI.grn_id INNER JOIN supplier S ON G.supplier_id = S.supplier_id INNER JOIN item I ON GI.item_id = I.item_id INNER JOIN grn_stock GS ON G.grn_id = GS.grn_id and GI.item_id=GS.item_id WHERE I.item_name like '%" + jtxt_Price_Update_Search.getText() + "%' && GS.stock_qty !='0' ");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("G.grn_id"));
                v.add(rs.getString("G.date"));
                v.add(rs.getString("S.name"));
                v.add(rs.getString("I.item_id"));
                v.add(rs.getString("I.item_name"));
                v.add(rs.getString("GS.stock_qty"));
                v.add(rs.getString("GI.supplier_price"));
                v.add(rs.getString("GI.selling_price"));
                v.add(rs.getString("GS.selling_price"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxt_Price_Update_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Price_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Price_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Price_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Price_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Price_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JButton jbtn_Price_Update_Price_Update;
    private javax.swing.JTextField jlbl_Price_Update_Discount;
    private javax.swing.JLabel jlbl_Price_Update_GRN_Date;
    private javax.swing.JLabel jlbl_Price_Update_GRN_ID;
    private javax.swing.JLabel jlbl_Price_Update_Item_ID;
    private javax.swing.JLabel jlbl_Price_Update_Product_Name;
    private javax.swing.JLabel jlbl_Price_Update_Stock_Selling_Price;
    private javax.swing.JLabel jlbl_Price_Update_Supplier_Price;
    private javax.swing.JTextField jlbl_Price_Update_Update_Selling_Price;
    private javax.swing.JTable jtbl_Price_Update;
    private javax.swing.JLabel jtxt_Price_Supplier_ID;
    private javax.swing.JTextField jtxt_Price_Update_Search;
    private javax.swing.JLabel jtxtl_Price_Update_Supplier_Name;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Date1;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Time1;
    // End of variables declaration//GEN-END:variables

private void DateandTime() {
        Timer t = new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf_Time = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat sdf_Date = new SimpleDateFormat("YYYY  MMMM  dd EEEE");
                SimpleDateFormat sdf_Date1 = new SimpleDateFormat("YYYY-MM-dd");
                String time = sdf_Time.format(d);
                String Date = sdf_Date.format(d);
                String Date1 = sdf_Date1.format(d);
                lbl_Time.setText(time);
                lbl_Date.setText(Date);
                lbl_Date1.setText(Date1);
            }
        });
        t.start();
    }

private void GRN_Update() {

        try {
            DefaultTableModel dtm1 = (DefaultTableModel) jtbl_Price_Update.getModel();

            ResultSet rs1 = new Database_Connection.DB().getData("SELECT * FROM grn G INNER JOIN grn_item GI ON G.grn_id = GI.grn_id INNER JOIN supplier S ON G.supplier_id = S.supplier_id INNER JOIN item I ON GI.item_id = I.item_id INNER JOIN grn_stock GS ON G.grn_id = GS.grn_id and GI.item_id=GS.item_id WHERE GS.stock_qty !='0' and GI.item_id");// and GI.item_id
            dtm1.setRowCount(0);
            while (rs1.next()) {

                Vector v = new Vector();
                v.add(rs1.getString("G.grn_id"));
                v.add(rs1.getString("G.date"));
                v.add(rs1.getString("S.name"));
                v.add(rs1.getString("I.item_id"));
                v.add(rs1.getString("I.item_name"));
                v.add(rs1.getString("GS.stock_qty"));
                v.add(rs1.getString("GI.supplier_price"));
                v.add(rs1.getString("GI.selling_price"));
                v.add(rs1.getString("GS.selling_price"));
                dtm1.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e);
        }
    }


private void Price_Update_Table_Loader_Data() {

        try {
            DefaultTableModel dtm1 = (DefaultTableModel) jtbl_Price_Update.getModel();

            ResultSet rs1 = new Database_Connection.DB().getData("SELECT * FROM grn G INNER JOIN grn_item GI ON G.grn_id = GI.grn_id INNER JOIN supplier S ON G.supplier_id = S.supplier_id INNER JOIN item I ON GI.item_id = I.item_id INNER JOIN grn_stock GS ON G.grn_id = GS.grn_id and GI.item_id=GS.item_id WHERE GS.stock_qty !='0' and GI.item_id");// and GI.item_id
            dtm1.setRowCount(0);
            while (rs1.next()) {

                Vector v = new Vector();
                v.add(rs1.getString("G.grn_id"));
                v.add(rs1.getString("G.date"));
                v.add(rs1.getString("S.name"));
                v.add(rs1.getString("I.item_id"));
                v.add(rs1.getString("I.item_name"));
                v.add(rs1.getString("GS.stock_qty"));
                v.add(rs1.getString("GI.supplier_price"));
                v.add(rs1.getString("GI.selling_price"));
                v.add(rs1.getString("GS.selling_price"));
                dtm1.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e);
        }
    }


private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
    }
    
}
