/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Database_Connection.DB;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilanka
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public User() {
        initComponents();
        DateandTime();
        User_ID_Auto_Loader();
        User_Table_Loader_Data();
        setIcon();
        jtbl_Staff.getTableHeader().setFont(new Font("Helvetica", Font.PLAIN, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_Time = new javax.swing.JLabel();
        lbl_Date = new javax.swing.JLabel();
        lbl_Time1 = new javax.swing.JLabel();
        lbl_Date1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jlbl_User_ID = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jtxt_Staff_Name = new javax.swing.JTextField();
        jPassword_Staff = new javax.swing.JPasswordField();
        jPassword_Retype_Staff = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jcmb_User_type = new javax.swing.JComboBox();
        jcmb_Staff_Status = new javax.swing.JComboBox();
        jbtn_Staff_Save = new javax.swing.JButton();
        jbtn_Staff_Update = new javax.swing.JButton();
        jbtn_User_Delete = new javax.swing.JButton();
        jbtn_Staff_Clear = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtbl_Staff = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jtxt_Staff_Search = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MINO TOP LOGO.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize-38_1.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-38_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Lock-38_1.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-cancel-38.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_Time.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Time.setText("Time");

        lbl_Date.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date.setText("Date");

        lbl_Time1.setFont(new java.awt.Font("Euphemia", 0, 30)); // NOI18N
        lbl_Time1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Time1.setText("Users");

        lbl_Date1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setFont(new java.awt.Font("Euphemia", 0, 16)); // NOI18N
        lbl_Date1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Date1.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(lbl_Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Date))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel52.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbl_User_ID.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jlbl_User_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel31.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel31.setText("User ID");

        jLabel32.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel32.setText("User Name");

        jtxt_Staff_Name.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Staff_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Staff_NameActionPerformed(evt);
            }
        });
        jtxt_Staff_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Staff_NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_Staff_NameKeyTyped(evt);
            }
        });

        jPassword_Staff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPassword_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_StaffActionPerformed(evt);
            }
        });
        jPassword_Staff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword_StaffKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassword_StaffKeyTyped(evt);
            }
        });

        jPassword_Retype_Staff.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPassword_Retype_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_Retype_StaffActionPerformed(evt);
            }
        });
        jPassword_Retype_Staff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword_Retype_StaffKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassword_Retype_StaffKeyTyped(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel34.setText("Retype Password");

        jLabel33.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel33.setText("Password");

        jLabel35.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel35.setText("User Type");

        jcmb_User_type.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jcmb_User_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin" }));
        jcmb_User_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_User_typeActionPerformed(evt);
            }
        });
        jcmb_User_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_User_typeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcmb_User_typeKeyReleased(evt);
            }
        });

        jcmb_Staff_Status.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jcmb_Staff_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Deactive" }));
        jcmb_Staff_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_Staff_StatusActionPerformed(evt);
            }
        });
        jcmb_Staff_Status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_Staff_StatusKeyPressed(evt);
            }
        });

        jbtn_Staff_Save.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_Staff_Save.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_Staff_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        jbtn_Staff_Save.setFocusable(false);
        jbtn_Staff_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Staff_SaveActionPerformed(evt);
            }
        });
        jbtn_Staff_Save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtn_Staff_SaveKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtn_Staff_SaveKeyReleased(evt);
            }
        });

        jbtn_Staff_Update.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_Staff_Update.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_Staff_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        jbtn_Staff_Update.setFocusable(false);
        jbtn_Staff_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Staff_UpdateActionPerformed(evt);
            }
        });

        jbtn_User_Delete.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_User_Delete.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_User_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        jbtn_User_Delete.setFocusable(false);
        jbtn_User_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_User_DeleteActionPerformed(evt);
            }
        });

        jbtn_Staff_Clear.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_Staff_Clear.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jbtn_Staff_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Clear.png"))); // NOI18N
        jbtn_Staff_Clear.setFocusable(false);
        jbtn_Staff_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_Staff_ClearActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jtbl_Staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbl_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "Password", "User Type"
            }
        ));
        jtbl_Staff.setFocusable(false);
        jtbl_Staff.setRowHeight(20);
        jtbl_Staff.getTableHeader().setReorderingAllowed(false);
        jtbl_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_StaffMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jtbl_Staff);
        if (jtbl_Staff.getColumnModel().getColumnCount() > 0) {
            jtbl_Staff.getColumnModel().getColumn(0).setMinWidth(75);
            jtbl_Staff.getColumnModel().getColumn(0).setPreferredWidth(75);
            jtbl_Staff.getColumnModel().getColumn(0).setMaxWidth(75);
            jtbl_Staff.getColumnModel().getColumn(2).setMinWidth(200);
            jtbl_Staff.getColumnModel().getColumn(2).setPreferredWidth(200);
            jtbl_Staff.getColumnModel().getColumn(2).setMaxWidth(200);
            jtbl_Staff.getColumnModel().getColumn(3).setMinWidth(100);
            jtbl_Staff.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtbl_Staff.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel36.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel36.setText("Search");

        jtxt_Staff_Search.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jtxt_Staff_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_Staff_SearchKeyReleased(evt);
            }
        });

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Euphemia", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(61, 61, 61)
                                .addComponent(jtxt_Staff_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPassword_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_User_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPassword_Retype_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(67, 67, 67)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcmb_User_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcmb_Staff_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jbtn_Staff_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn_Staff_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn_User_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn_Staff_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_Staff_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_Staff_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(375, 375, 375)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_User_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(jtxt_Staff_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPassword_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPassword_Retype_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcmb_User_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcmb_Staff_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jbtn_Staff_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtn_Staff_Clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jbtn_Staff_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jbtn_User_Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            setExtendedState(Customer.ICONIFIED);
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','System Minimized')");
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Admin Menu')");
            new Admin_Menu().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Back Logged into to Login')");
            new Login().setVisible(true);
            this.dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new DB().putData("INSERT INTO logger (user_name,date, time,description) VALUE('" + Login.User_Name + "','" + lbl_Date1.getText() + "','" + lbl_Time.getText() + "','Has been Exit from the System')");
            System.exit(0);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxt_Staff_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Staff_NameActionPerformed
        jPassword_Staff.grabFocus();
    }//GEN-LAST:event_jtxt_Staff_NameActionPerformed

    private void jtxt_Staff_NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Staff_NameKeyReleased
        if (jtxt_Staff_Name.getText().isEmpty()) {

            ImageIcon IC_M;
            IC_M = new ImageIcon(getClass().getResource("question.png"));
            jLabel52.setIcon(IC_M);

        } else {
            try {
                ResultSet rs = new DB().getData("select user_name from user where user_name like '" + jtxt_Staff_Name.getText() + "'");
                while (rs.next()) {
                    jLabel53.setText(rs.getString("user_name"));
                }
                if (jtxt_Staff_Name.getText().equals(jLabel53.getText())) {
                    ImageIcon IC_M;
                    IC_M = new ImageIcon(getClass().getResource("wrong.png"));
                    jLabel52.setIcon(IC_M);
                } else {
                    ImageIcon IC_M;
                    IC_M = new ImageIcon(getClass().getResource("Right.png"));
                    jLabel52.setIcon(IC_M);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jtxt_Staff_NameKeyReleased

    private void jtxt_Staff_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Staff_NameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Staff_NameKeyTyped

    private void jPassword_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_StaffActionPerformed
        jPassword_Retype_Staff.grabFocus();
    }//GEN-LAST:event_jPassword_StaffActionPerformed

    private void jPassword_StaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_StaffKeyReleased
        if (jPassword_Staff.getText().isEmpty() && jPassword_Retype_Staff.getText().isEmpty()) {

            ImageIcon IC_M;
            IC_M = new ImageIcon(getClass().getResource("question.png"));
            jLabel51.setIcon(IC_M);

        } else {
            if (jPassword_Retype_Staff.getText().equals(jPassword_Staff.getText())) {
                ImageIcon IC_M;
                IC_M = new ImageIcon(getClass().getResource("Right.png"));
                jLabel51.setIcon(IC_M);

            } else {
                ImageIcon IC_M;
                IC_M = new ImageIcon(getClass().getResource("wrong.png"));
                jLabel51.setIcon(IC_M);

            }
        }
    }//GEN-LAST:event_jPassword_StaffKeyReleased

    private void jPassword_StaffKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_StaffKeyTyped

    }//GEN-LAST:event_jPassword_StaffKeyTyped

    private void jPassword_Retype_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_Retype_StaffActionPerformed
        jcmb_User_type.grabFocus();
    }//GEN-LAST:event_jPassword_Retype_StaffActionPerformed

    private void jPassword_Retype_StaffKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_Retype_StaffKeyReleased
        if (jPassword_Staff.getText().isEmpty() && jPassword_Retype_Staff.getText().isEmpty()) {

            ImageIcon IC_M;
            IC_M = new ImageIcon(getClass().getResource("question.png"));
            jLabel51.setIcon(IC_M);

        } else {
            if (jPassword_Retype_Staff.getText().equals(jPassword_Staff.getText())) {
                ImageIcon IC_M;
                IC_M = new ImageIcon(getClass().getResource("Right.png"));
                jLabel51.setIcon(IC_M);

            } else {
                ImageIcon IC_M;
                IC_M = new ImageIcon(getClass().getResource("wrong.png"));
                jLabel51.setIcon(IC_M);

            }
        }
    }//GEN-LAST:event_jPassword_Retype_StaffKeyReleased

    private void jPassword_Retype_StaffKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_Retype_StaffKeyTyped

    }//GEN-LAST:event_jPassword_Retype_StaffKeyTyped

    private void jcmb_User_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_User_typeActionPerformed
        // jcmb_Staff_Status.grabFocus;
    }//GEN-LAST:event_jcmb_User_typeActionPerformed

    private void jcmb_User_typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_User_typeKeyPressed
        char c = evt.getKeyChar();
        if (c == evt.VK_ENTER) {

            jcmb_Staff_Status.grabFocus();
        }
    }//GEN-LAST:event_jcmb_User_typeKeyPressed

    private void jcmb_User_typeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_User_typeKeyReleased

    }//GEN-LAST:event_jcmb_User_typeKeyReleased

    private void jcmb_Staff_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_Staff_StatusActionPerformed

    }//GEN-LAST:event_jcmb_Staff_StatusActionPerformed

    private void jcmb_Staff_StatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_Staff_StatusKeyPressed
        char c1 = evt.getKeyChar();
        if (c1 == evt.VK_ENTER) {

            if (!jLabel53.getText().equals(jtxt_Staff_Name.getText())) {
                if (!jlbl_User_ID.getText().isEmpty() && !jtxt_Staff_Name.getText().isEmpty() && !jPassword_Staff.getText().isEmpty() && !jPassword_Retype_Staff.getText().isEmpty()) {
                    if (jPassword_Retype_Staff.getText().equals(jPassword_Staff.getText())) {

                        System.out.println("OK");
                        try {

                            int Status = 0;

                            if (jcmb_Staff_Status.getSelectedItem().toString().equals("Active")) {
                                Status += 1;
                            }
                            if (jcmb_Staff_Status.getSelectedItem().toString().equals("Deactive")) {
                                Status += 0;
                            }

                            new DB().putData("INSERT INTO user (user_id,user_name, password,user_type, status) VALUE('" + jlbl_User_ID.getText() + "','" + jtxt_Staff_Name.getText() + "','" + jPassword_Staff.getText() + "','" + jcmb_User_type.getSelectedItem() + "','" + Status + "')");
                            JOptionPane.showMessageDialog(this, "User Registered Successfuly.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                            staff_text_clean();
                        } catch (Exception e) {
                            System.out.println(e);
                        }

                    } else {
                        System.out.println("Not Match Confirm Password.");
                        JOptionPane.showMessageDialog(this, "Not Match Confirm Password. \nRe Enter Your Password.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                        jPassword_Staff.setText(null);
                        jPassword_Retype_Staff.setText(null);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Check All Input Field Again. ", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                    jtxt_Staff_Name.setText(null);
                    jPassword_Staff.setText(null);
                    jPassword_Retype_Staff.setText(null);

                    System.out.println("Empty");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid User Name \nEnter another User Name.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                jtxt_Staff_Name.setText(null);
            }

            jtxt_Staff_Name.grabFocus();
        }
    }//GEN-LAST:event_jcmb_Staff_StatusKeyPressed

    private void jbtn_Staff_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Staff_SaveActionPerformed

        if (!jlbl_User_ID.getText().equals(id.getText())) {
            if (!jLabel53.getText().equals(jtxt_Staff_Name.getText())) {
                if (!jlbl_User_ID.getText().isEmpty() && !jtxt_Staff_Name.getText().isEmpty() && !jPassword_Staff.getText().isEmpty() && !jPassword_Retype_Staff.getText().isEmpty()) {
                    if (jPassword_Retype_Staff.getText().equals(jPassword_Staff.getText())) {

                        System.out.println("OK");
                        try {

                            int Status = 0;

                            if (jcmb_Staff_Status.getSelectedItem().toString().equals("Active")) {
                                Status += 1;
                            }
                            if (jcmb_Staff_Status.getSelectedItem().toString().equals("Deactive")) {
                                Status += 0;
                            }

                            new DB().putData("INSERT INTO user (user_id,user_name, password,user_type, status) VALUE('" + jlbl_User_ID.getText() + "','" + jtxt_Staff_Name.getText() + "','" + jPassword_Staff.getText() + "','" + jcmb_User_type.getSelectedItem() + "','" + Status + "')");
                            JOptionPane.showMessageDialog(this, "User Registered Successfuly.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                            staff_text_clean();
                        } catch (Exception e) {
                            System.out.println(e);
                        }

                    } else {
                        System.out.println("Not Match Confirm Password.");
                        JOptionPane.showMessageDialog(this, "Not Match Confirm Password. \nRe Enter Your Password.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                        jPassword_Staff.setText(null);
                        jPassword_Retype_Staff.setText(null);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Check All Input Field Again. ", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                    jtxt_Staff_Name.setText(null);
                    jPassword_Staff.setText(null);
                    jPassword_Retype_Staff.setText(null);

                    System.out.println("Empty");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid User Name \nEnter another User Name.", "Infromation Message", JOptionPane.INFORMATION_MESSAGE);
                jtxt_Staff_Name.setText(null);
            }
        }
        jtxt_Staff_Name.grabFocus();
    }//GEN-LAST:event_jbtn_Staff_SaveActionPerformed

    private void jbtn_Staff_SaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn_Staff_SaveKeyPressed

    }//GEN-LAST:event_jbtn_Staff_SaveKeyPressed

    private void jbtn_Staff_SaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn_Staff_SaveKeyReleased

    }//GEN-LAST:event_jbtn_Staff_SaveKeyReleased

    private void jbtn_Staff_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Staff_UpdateActionPerformed
            if (!jlbl_User_ID.getText().isEmpty() && !jtxt_Staff_Name.getText().isEmpty() && !jPassword_Staff.getText().isEmpty() && !jPassword_Retype_Staff.getText().isEmpty()) {
                if (jPassword_Retype_Staff.getText().equals(jPassword_Staff.getText())) {
                    try {
                        int Status = 0;
                        String user_type = "";
                        if (jcmb_User_type.getSelectedItem().toString().equals("Admin")) {
                            user_type += "Admin";
                        }
                        if (jcmb_User_type.getSelectedItem().toString().equals("User")) {
                            user_type += "User";
                        }
                        if (jcmb_Staff_Status.getSelectedItem().toString().equals("Active")) {
                            Status += 1;
                        }
                        if (jcmb_Staff_Status.getSelectedItem().toString().equals("Deactive")) {
                            Status += 0;
                        }
                        new DB().putData("UPDATE user SET user_name='" + jtxt_Staff_Name.getText() + "',password='" + jPassword_Staff.getText() + "',user_type='" + jcmb_User_type.getSelectedItem() + "',status='" + Status + "' WHERE user_id = '" + jlbl_User_ID.getText() + "'");
                        JOptionPane.showMessageDialog(this, "User Details Updated Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);
                        staff_text_clean();
                    } catch (Exception e) {
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Check All Input Field", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            }
        jtxt_Staff_Name.grabFocus();
    }//GEN-LAST:event_jbtn_Staff_UpdateActionPerformed

    private void jbtn_User_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_User_DeleteActionPerformed
        try {
            new DB().putData("UPDATE user SET user.delete='0' WHERE user_id = '" + jlbl_User_ID.getText() + "'");
            JOptionPane.showMessageDialog(this, "User Deleted Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);
            staff_text_clean();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtn_User_DeleteActionPerformed

    private void jbtn_Staff_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_Staff_ClearActionPerformed
        staff_text_clean();
        jtxt_Staff_Name.grabFocus();
    }//GEN-LAST:event_jbtn_Staff_ClearActionPerformed

    private void jtbl_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_StaffMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Staff.getModel();
        int Selected_Row = jtbl_Staff.getSelectedRow();
        jlbl_User_ID.setText(dtm.getValueAt(Selected_Row, 0).toString());
        id.setText(dtm.getValueAt(Selected_Row, 0).toString());
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT * FROM user WHERE user_id = '" + jlbl_User_ID.getText() + "'");
            while (rs.next()) {
                jtxt_Staff_Name.setText(rs.getString("user_name"));

                if (rs.getString("user_type").equals("Admin")) {
                    jcmb_User_type.setSelectedItem("Admin");
                } else {
                    jcmb_User_type.setSelectedItem("User");
                }

                if (rs.getString("status").equals("1")) {
                    jcmb_Staff_Status.setSelectedItem("Active");
                } else {
                    jcmb_Staff_Status.setSelectedItem("Deactive");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        jtxt_Staff_Name.grabFocus();
    }//GEN-LAST:event_jtbl_StaffMouseClicked

    private void jtxt_Staff_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_Staff_SearchKeyReleased
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Staff.getModel();
        try {
            ResultSet rs = new DB().getData("select * from user where user_name like '%" + jtxt_Staff_Search.getText() + "%'");
            dtm.setRowCount(0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));

                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtxt_Staff_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword_Retype_Staff;
    private javax.swing.JPasswordField jPassword_Staff;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jbtn_Staff_Clear;
    private javax.swing.JButton jbtn_Staff_Save;
    private javax.swing.JButton jbtn_Staff_Update;
    private javax.swing.JButton jbtn_User_Delete;
    private javax.swing.JComboBox jcmb_Staff_Status;
    private javax.swing.JComboBox jcmb_User_type;
    private javax.swing.JLabel jlbl_User_ID;
    private javax.swing.JTable jtbl_Staff;
    private javax.swing.JTextField jtxt_Staff_Name;
    private javax.swing.JTextField jtxt_Staff_Search;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JLabel lbl_Date1;
    private javax.swing.JLabel lbl_Time;
    private javax.swing.JLabel lbl_Time1;
    // End of variables declaration//GEN-END:variables

    private void DateandTime() {
        Timer t = new Timer(100, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf_Time = new SimpleDateFormat("hh:mm:ss aa");
                SimpleDateFormat sdf_Date = new SimpleDateFormat("YYYY  MMMM  dd EEEE");
                SimpleDateFormat sdf_Date1 = new SimpleDateFormat("YYYY-MM-dd");
                String time = sdf_Time.format(d);
                String Date = sdf_Date.format(d);
                String Date1 = sdf_Date1.format(d);
                lbl_Time.setText(time);
                lbl_Date.setText(Date);
                lbl_Date1.setText(Date1);
            }
        });
        t.start();
    }

    private void User_ID_Auto_Loader() {
        try {
            ResultSet rs = new Database_Connection.DB().getData("SELECT MAX(user_id) AS LargestID FROM user;");
            if (rs.next()) {
                String id = rs.getString("LargestID");
                jlbl_User_ID.setText(Integer.parseInt(id) + 1 + "");
            }
        } catch (Exception e) {
            System.out.println(e);
            jlbl_User_ID.setText("100");
            jtxt_Staff_Name.grabFocus();
        }
    }

    private void User_Table_Loader_Data() {
        DefaultTableModel dtm = (DefaultTableModel) jtbl_Staff.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet set = new DB().getData("Select * from user where user.delete !='0'");

            while (set.next()) {
                Vector v = new Vector();
                v.add(set.getString("user_id"));
                v.add(set.getString("user_name"));
                v.add(set.getString("password"));
                v.add(set.getString("user_type"));
                if (set.getString("status").equals("1")) {
                    v.add("Active");
                }
                if (set.getString("status").equals("0")) {
                    v.add("Deactive");
                }
                dtm.addRow(v);
            }
        } catch (Exception e) {
        }
    }

    private void staff_text_clean() {
        jtxt_Staff_Name.setText(null);
        jPassword_Staff.setText(null);
        jPassword_Retype_Staff.setText(null);
        jtxt_Staff_Search.setText(null);
        jcmb_User_type.setSelectedIndex(0);
        jcmb_Staff_Status.setSelectedIndex(0);
        jLabel52.setIcon(null);
        jLabel51.setIcon(null);
        User_ID_Auto_Loader();
        User_Table_Loader_Data();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.png")));
    }

}
